# Advertisment

## Easy as MATLAB, flexible as Python, deep as Lisp, fast as Fortran.
John F. Gibson, [*WhyJulia*](https://github.com/johnfgibson/whyjulia/blob/master/1-whyjulia.ipynb).

## 1. Some mathematical code

## Warmup

In [1]:
using Colors, Plots, Libdl, BenchmarkTools, Statistics

## Close to $+\infty$ starting time for everything. It is Julia tradition

## Quick presentation

In [2]:
σ₁ = [0 1;
      1 0];
σ₂ = [0 -im;
      im 0];
σ₃ = [1  0;
      0 -1]

2×2 Array{Int64,2}:
 1   0
 0  -1

In [3]:
σ₁ * σ₂

2×2 Array{Complex{Int64},2}:
 0+1im  0+0im
 0+0im  0-1im

In [4]:
σ₁ * σ₃

2×2 Array{Int64,2}:
 0  -1
 1   0

In [5]:
σ₁^2

2×2 Array{Int64,2}:
 1  0
 0  1

In [6]:
n = 1_000

1000

In [7]:
n * σ₁

2×2 Array{Int64,2}:
    0  1000
 1000     0

In [8]:
pi

π = 3.1415926535897...

In [9]:
π

π = 3.1415926535897...

In [10]:
x = 1
y = 2

2

In [11]:
println("$x + $y = $(x + y)")

1 + 2 = 3


In [12]:
println("σ₂ = $(σ₂)")

σ₂ = Complex{Int64}[0+0im 0-1im; 0+1im 0+0im]


## Unfortunetly
Unicode restrain Julia (C#, Rust, etc.) abilitis to use super- and subscripts limiting it to 30 concret case. It should be at least 2 $\times$ bigger. By there is a hope, that Unicode will be updated, look [*Unicode Proposal to Encode Subscripts/Superscripts for Mathematical Programming*](https://github.com/stevengj/subsuper-proposal).

## Starting again with basics things

In [13]:
1//3

1//3

In [14]:
1//3 + 1//2

5//6

In [15]:
1/3

0.3333333333333333

In [16]:
convert(Rational{Int32}, 1/3)

1//3

In [17]:
convert(Rational{Int64}, 1/3)

6004799503160661//18014398509481984

In [18]:
a = "Zakład Teorii "
b = "Pola"

"Pola"

In [19]:
a * b

"Zakład Teorii Pola"

In [20]:
"pole "^100

"pole pole pole pole pole pole pole pole pole pole pole pole pole pole pole pole pole pole pole pole pole pole pole pole pole pole pole pole pole pole pole pole pole pole pole pole pole pole pole pole pole pole pole pole pole pole pole pole pole pole pole pole pole pole pole pole pole pole pole pole pole pole pole pole pole pole pole pole pole pole pole pole pole pole pole pole pole pole pole pole pole pole pole pole pole pole pole pole pole pole pole pole pole pole pole pole pole pole pole pole "

In [21]:
v₁ = [1 2 0]

1×3 Array{Int64,2}:
 1  2  0

In [22]:
v₂ = [0 -2 3]

1×3 Array{Int64,2}:
 0  -2  3

In [23]:
v₁ + v₂

1×3 Array{Int64,2}:
 1  0  3

In [24]:
v₂ = [2, 1, 0]  # Proper vector

3-element Array{Int64,1}:
 2
 1
 0

In [25]:
v₁ * v₂

1-element Array{Int64,1}:
 4

In [26]:
v₁'

3×1 LinearAlgebra.Adjoint{Int64,Array{Int64,2}}:
 1
 2
 0

In [27]:
v₂'v₂

5

In [28]:
v₁'v₁

3×3 Array{Int64,2}:
 1  2  0
 2  4  0
 0  0  0

In [29]:
using LinearAlgebra

In [30]:
v₁ ⋅ v₁

5

$v_{ 2 } \times v_{ 2 }$

In [31]:
v₂ × v₂

3-element Array{Int64,1}:
 0
 0
 0

In [ ]:
?×

In [32]:
A = [0 1; 1 0]

2×2 Array{Int64,2}:
 0  1
 1  0

In [33]:
typeof(A)

Array{Int64,2}

In [34]:
issymmetric(A)

true

In [35]:
eigen(A)

Eigen{Float64,Float64,Array{Float64,2},Array{Float64,1}}
eigenvalues:
2-element Array{Float64,1}:
 -1.0
  1.0
eigenvectors:
2×2 Array{Float64,2}:
 -0.707107  0.707107
  0.707107  0.707107

In [36]:
?eigen

search: eigen eigen! Eigen GeneralizedEigen weighted_color_mean eigvecs



```
eigen(A; permute::Bool=true, scale::Bool=true) -> Eigen
```

Computes the eigenvalue decomposition of `A`, returning an `Eigen` factorization object `F` which contains the eigenvalues in `F.values` and the eigenvectors in the columns of the matrix `F.vectors`. (The `k`th eigenvector can be obtained from the slice `F.vectors[:, k]`.)

Iterating the decomposition produces the components `F.values` and `F.vectors`.

The following functions are available for `Eigen` objects: [`inv`](@ref), [`det`](@ref), and [`isposdef`](@ref).

For general nonsymmetric matrices it is possible to specify how the matrix is balanced before the eigenvector calculation. The option `permute=true` permutes the matrix to become closer to upper triangular, and `scale=true` scales the matrix by its diagonal elements to make rows and columns more equal in norm. The default is `true` for both options.

# Examples

```jldoctest
julia> F = eigen([1.0 0.0 0.0; 0.0 3.0 0.0; 0.0 0.0 18.0])
Eigen{Float64,Float64,Array{Float64,2},Array{Float64,1}}
eigenvalues:
3-element Array{Float64,1}:
  1.0
  3.0
 18.0
eigenvectors:
3×3 Array{Float64,2}:
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0

julia> F.values
3-element Array{Float64,1}:
  1.0
  3.0
 18.0

julia> F.vectors
3×3 Array{Float64,2}:
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0

julia> vals, vecs = F; # destructuring via iteration

julia> vals == F.values && vecs == F.vectors
true
```

---

```
eigen(A, B) -> GeneralizedEigen
```

Computes the generalized eigenvalue decomposition of `A` and `B`, returning a `GeneralizedEigen` factorization object `F` which contains the generalized eigenvalues in `F.values` and the generalized eigenvectors in the columns of the matrix `F.vectors`. (The `k`th generalized eigenvector can be obtained from the slice `F.vectors[:, k]`.)

Iterating the decomposition produces the components `F.values` and `F.vectors`.

# Examples

```jldoctest
julia> A = [1 0; 0 -1]
2×2 Array{Int64,2}:
 1   0
 0  -1

julia> B = [0 1; 1 0]
2×2 Array{Int64,2}:
 0  1
 1  0

julia> F = eigen(A, B);

julia> F.values
2-element Array{Complex{Float64},1}:
 0.0 + 1.0im
 0.0 - 1.0im

julia> F.vectors
2×2 Array{Complex{Float64},2}:
  0.0-1.0im   0.0+1.0im
 -1.0-0.0im  -1.0+0.0im

julia> vals, vecs = F; # destructuring via iteration

julia> vals == F.values && vecs == F.vectors
true
```

---

```
eigen(A::Union{SymTridiagonal, Hermitian, Symmetric}, irange::UnitRange) -> Eigen
```

Computes the eigenvalue decomposition of `A`, returning an `Eigen` factorization object `F` which contains the eigenvalues in `F.values` and the eigenvectors in the columns of the matrix `F.vectors`. (The `k`th eigenvector can be obtained from the slice `F.vectors[:, k]`.)

Iterating the decomposition produces the components `F.values` and `F.vectors`.

The following functions are available for `Eigen` objects: [`inv`](@ref), [`det`](@ref), and [`isposdef`](@ref).

The `UnitRange` `irange` specifies indices of the sorted eigenvalues to search for.

!!! note
    If `irange` is not `1:n`, where `n` is the dimension of `A`, then the returned factorization will be a *truncated* factorization.


---

```
eigen(A::Union{SymTridiagonal, Hermitian, Symmetric}, vl::Real, vu::Real) -> Eigen
```

Computes the eigenvalue decomposition of `A`, returning an `Eigen` factorization object `F` which contains the eigenvalues in `F.values` and the eigenvectors in the columns of the matrix `F.vectors`. (The `k`th eigenvector can be obtained from the slice `F.vectors[:, k]`.)

Iterating the decomposition produces the components `F.values` and `F.vectors`.

The following functions are available for `Eigen` objects: [`inv`](@ref), [`det`](@ref), and [`isposdef`](@ref).

`vl` is the lower bound of the window of eigenvalues to search for, and `vu` is the upper bound.

!!! note
    If [`vl`, `vu`] does not contain all eigenvalues of `A`, then the returned factorization will be a *truncated* factorization.



In [37]:
eigen_A = eigen(A)

Eigen{Float64,Float64,Array{Float64,2},Array{Float64,1}}
eigenvalues:
2-element Array{Float64,1}:
 -1.0
  1.0
eigenvectors:
2×2 Array{Float64,2}:
 -0.707107  0.707107
  0.707107  0.707107

In [38]:
eigen_A.values

2-element Array{Float64,1}:
 -1.0
  1.0

In [39]:
eigen_A.vectors

2×2 Array{Float64,2}:
 -0.707107  0.707107
  0.707107  0.707107

In [40]:
eigen_A.vectors[:, 1]

2-element Array{Float64,1}:
 -0.7071067811865475
  0.7071067811865475

# 2. Multiple dispatch

In [41]:
f(x) = 2(x - 1)^2

f (generic function with 1 method)

In [42]:
f(0)

2

In [43]:
f(1)

0

In [44]:
f(0.0)

2.0

In [ ]:
f(1.0)

In [45]:
f(σ₁)

MethodError: MethodError: no method matching -(::Array{Int64,2}, ::Int64)
Closest candidates are:
  -(!Matched::Complex{Bool}, ::Real) at complex.jl:298
  -(!Matched::Missing, ::Number) at missing.jl:93
  -(!Matched::Base.CoreLogging.LogLevel, ::Integer) at logging.jl:107
  ...

In [46]:
oneunit(0)

1

In [47]:
oneunit(Int64)

1

In [ ]:
[1 2; 3 4]

In [48]:
oneunit([1 2; 3 4])

2×2 Array{Int64,2}:
 1  0
 0  1

In [49]:
g(x) = 2(x - oneunit(x))^2

g (generic function with 1 method)

In [50]:
g(0)

2

In [ ]:
g(1)

In [51]:
g(0.0)

2.0

In [52]:
g(σ₁)

2×2 Array{Int64,2}:
  4  -4
 -4   4

In [53]:
@code_typed f(0)

CodeInfo(
│╻  -1 1 ─ %1 = (Base.sub_int)(x, 1)::Int64
││╻  *  │   %2 = (Base.mul_int)(%1, %1)::Int64
│╻  *  │   %3 = (Base.mul_int)(2, %2)::Int64
│    └──      return %3
) => Int64

In [ ]:
@code_typed f(0.0)

In [ ]:
@code_warntype f(0)

In [ ]:
@code_lowered f(0)

In [ ]:
@code_llvm f(0)

In [54]:
@code_native f(0)

	.text
; Function f {
; Location: In[41]:1
; Function -; {
; Location: In[41]:1
	addq	$-1, %rdi
;}
; Function *; {
; Location: int.jl:54
	imulq	%rdi, %rdi
	leaq	(%rdi,%rdi), %rax
;}
	retq
	nopl	(%rax)
;}


In [ ]:
@code_typed g(0)

In [ ]:
@code_typed g(0.0)

In [ ]:
g(im)

In [ ]:
@code_typed g(im)

In [ ]:
@code_typed g(σ₁)

In [ ]:
@code_warntype g(σ₁)

In [ ]:
@code_lowered g(σ₁)

In [ ]:
@code_llvm g(σ₁)

In [ ]:
@code_native g(σ₁)

In [55]:
methods(eigen)

# 19 methods for generic function "eigen":
[1] eigen(A::SymTridiagonal{T,V} where V<:AbstractArray{T,1}) where T in LinearAlgebra at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/LinearAlgebra/src/tridiag.jl:201
[2] eigen(A::SymTridiagonal{T,V} where V<:AbstractArray{T,1}, irange::UnitRange) where T in LinearAlgebra at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/LinearAlgebra/src/tridiag.jl:205
[3] eigen(A::SymTridiagonal{T,V} where V<:AbstractArray{T,1}, vl::Real, vu::Real) where T in LinearAlgebra at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/LinearAlgebra/src/tridiag.jl:210
[4] eigen(A::LinearAlgebra.AbstractTriangular) in LinearAlgebra at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/LinearAlgebra/src/triangular.jl:2466
[5] eigen(A::Union{DenseArray{T,2}, ReinterpretArray{T,2,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Tuple{AbstractUnitRange,Vararg{Any,N} where N} where A<:DenseArray where N where T, DenseArray}, ReshapedArray{T,2,A,MI} where MI<:Tuple{Vararg{SignedMultiplicativeInverse{Int64},N} where N} where A<:Union{ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Tuple{AbstractUnitRange,Vararg{Any,N} where N} where A<:DenseArray where N where T, DenseArray} where N where T, SubArray{T,N,A,I,true} where I<:Tuple{AbstractUnitRange,Vararg{Any,N} where N} where A<:DenseArray where N where T, DenseArray}, SubArray{T,2,A,I,L} where L where I<:Tuple{Vararg{Union{Int64, AbstractRange{Int64}, AbstractCartesianIndex},N} where N} where A<:Union{ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Tuple{AbstractUnitRange,Vararg{Any,N} where N} where A<:DenseArray where N where T, DenseArray} where N where T, ReshapedArray{T,N,A,MI} where MI<:Tuple{Vararg{SignedMultiplicativeInverse{Int64},N} where N} where A<:Union{ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Tuple{AbstractUnitRange,Vararg{Any,N} where N} where A<:DenseArray where N where T, DenseArray} where N where T, SubArray{T,N,A,I,true} where I<:Tuple{AbstractUnitRange,Vararg{Any,N} where N} where A<:DenseArray where N where T, DenseArray} where N where T, DenseArray}}; permute, scale) where T in LinearAlgebra at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/LinearAlgebra/src/eigen.jl:116
[6] eigen(x::Number) in LinearAlgebra at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/LinearAlgebra/src/eigen.jl:120
[7] eigen(A::Hermitian{#s174,#s173} where #s173<:(StaticArrays.StaticArray{Tuple{N,M},T,2} where T where M where N) where #s174<:Real; kwargs...) in StaticArrays at /home/kamilfvt/.julia/packages/StaticArrays/WmJnA/src/eigen.jl:399
[8] eigen(A::Hermitian{#s174,#s173} where #s173<:(StaticArrays.StaticArray{Tuple{N,M},T,2} where T where M where N) where #s174<:Complex; kwargs...) in StaticArrays at /home/kamilfvt/.julia/packages/StaticArrays/WmJnA/src/eigen.jl:400
[9] eigen(A::Symmetric{#s174,#s173} where #s173<:(StaticArrays.StaticArray{Tuple{N,M},T,2} where T where M where N) where #s174<:Real; kwargs...) in StaticArrays at /home/kamilfvt/.julia/packages/StaticArrays/WmJnA/src/eigen.jl:401
[10] eigen(A::Symmetric{#s174,#s173} where #s173<:(StaticArrays.StaticArray{Tuple{N,M},T,2} where T where M where N) where #s174<:Complex; kwargs...) in StaticArrays at /home/kamilfvt/.julia/packages/StaticArrays/WmJnA/src/eigen.jl:402
[11] eigen(A::Union{Hermitian{T,S}, Hermitian{Complex{T},S}, Symmetric{T,S}} where S where T<:Real) in LinearAlgebra at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/LinearAlgebra/src/symmetric.jl:490
[12] eigen(A::Union{Hermitian{T,S}, Hermitian{Complex{T},S}, Symmetric{T,S}} where S where T<:Real, irange::UnitRange) in LinearAlgebra at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/LinearAlgebra/src/symmetric.jl:515
[13] eigen(D::Diagonal; permute, sca

In [ ]:
eigen(A)

# 3. Random numbers and matrics.

In [ ]:
rand(5)

In [ ]:
randn(5)

In [ ]:
rand(3, 3)

In [ ]:
rand(3, 3, 3)

In [ ]:
1:4

In [ ]:
A = rand(1:4, 3, 3)

In [ ]:
distinguishable_colors(20)

In [ ]:
palette = distinguishable_colors(20)

In [ ]:
rand(palette, 5, 5)

# 4. There are lies, big lies and benchmarks

Examples taken from
[*Julia is fast*](https://github.com/JuliaComputing/JuliaBoxTutorials/blob/master/introductory-tutorials/intro-to-julia/09.%20Julia%20is%20fast.ipynb) at JuliaComputing GitHub account.

We test speed of Julia using simple case of function summing elements of vector $V$ with $N = 10^{ 7 }$ random elements
\begin{equation}
    \textrm{sum}(V) = \sum_{ i = 1 }^{ N } V_{ i }.
\end{equation}

## Function in Julia are faster that "free" code.

In [ ]:
gr()
V = rand(10^7)  # 1D vector of random numbers, uniform on [0,1)

In [ ]:
sum(V) / 10^7

## 4.1 The C language, by `gcc`

I don't write this C code.

In [ ]:
C_code = """
#include <stddef.h>
double c_sum(size_t n, double *X) {
    double s = 0.0;
    for (size_t i = 0; i < n; ++i) {
        s += X[i];
    }
    return s;
}
"""

const Clib = tempname()   # make a temporary file


# compile to a shared library by piping C_code to gcc
# (works only if you have gcc installed):

open(`gcc -fPIC -O3 -msse3 -xc -shared -o $(Clib * "." * Libdl.dlext) -`, "w") do f
    print(f, C_code) 
end

# define a Julia function that calls the C function:
c_sum(X::Array{Float64}) = ccall(("c_sum", Clib), Float64, (Csize_t, Ptr{Float64}), length(X), X)

Approx

In [ ]:
(c_sum(V) - sum(V)) / 10^7

In [ ]:
c_bench = @benchmark c_sum($V)

In [ ]:
d_min = Dict("C" => minimum(c_bench.times) / 1e6)  # We creat efficient dictionary
d_med = Dict("C" => median(c_bench.times) / 1e6)

In [ ]:
t = c_bench.times / 1e6

In [ ]:
min_t = 3.0
max_t = 12.0

histogram(t, bins=500,
             title="Benchmarks for hand-written C",
             xlim=(min_t, max_t),
             xlabel="milliseconds", ylabel="count", label="")

## 4.2 C with `gcc -ffast-math`

I don't write this code either.

In [ ]:
const Clib_fastmath = tempname()   # make a temporary file

# The same as above but with a -ffast-math flag added
open(`gcc -fPIC -O3 -msse3 -xc -shared -ffast-math -o $(Clib_fastmath * "." * Libdl.dlext) -`, "w") do f
    print(f, C_code) 
end

# define a Julia function that calls the C function:
c_sum_fastmath(X::Array{Float64}) = ccall(("c_sum", Clib_fastmath), Float64, (Csize_t, Ptr{Float64}), length(X), X)

In [ ]:
c_fastmath_bench = @benchmark $c_sum_fastmath($V)
d_min["C -ffast-math"] = minimum(c_fastmath_bench.times) / 1e6  # in milliseconds
d_med["C -ffast-math"] = median(c_fastmath_bench.times) / 1e6

t = c_fastmath_bench.times / 1e6 # times in milliseconds

histogram(t, bins=500,
             title="Benchmarks for hand-written C with -ffast-math",
             xlim=(min_t, max_t),
             xlabel="milliseconds", ylabel="count", label="")

In [ ]:
min_t = 4.0
max_t = 12.0

histogram(t, bins=500,
             title="Benchmarks for hand-written C with -ffast-math",
             xlim=(min_t, max_t),
             xlabel="milliseconds", ylabel="count", label="")

## 4.3 Julia (built-in)

In [ ]:
@which sum(V)  # This code on GitHub tell you probably nothing

In [ ]:
j_bench = @benchmark sum($V)
d_min["Julia built-in"] = minimum(j_bench.times) / 1e6  # in milliseconds
d_med["Julia built-in"] = median(j_bench.times) / 1e6

t = j_bench.times / 1e6 # times in milliseconds

histogram(t, bins=500,
             title="Benchmarks for Julia built-in sum function",
             xlim=(min_t, max_t),
             xlabel="milliseconds", ylabel="count", label="")

In [ ]:
min_t = 4.0
max_t = 12.0

histogram(t, bins=500,
             title="Benchmarks for Julia built-in sum function",
             xlim=(min_t, max_t),
             xlabel="milliseconds", ylabel="count", label="")

## 4.4 Julia, hand-written

In [ ]:
function my_sum(V)   
    s = 0.0 # s = zero(eltype(a))
    for v in V
        s += v
    end
    s
end

j_bench_hand = @benchmark my_sum($V)
d_min["Julia hand-written"] = minimum(j_bench_hand.times) / 1e6  # in milliseconds
d_med["Julia hand-written"] = median(j_bench_hand.times) / 1e6

t = j_bench_hand.times / 1e6  # times in milliseconds

histogram(t, bins=500,
             title="Benchmarks for Julia hand-written sum function",
             xlim=(min_t, max_t),
             xlabel="milliseconds", ylabel="count", label="")

In [ ]:
min_t = 4
max_t = 12

histogram(t, bins=500,
             title="Benchmarks for Julia hand-written sum function",
             xlim=(min_t, max_t),
             xlabel="milliseconds", ylabel="count", label="")

## 4.5 Julia hand-written with `@simd`

In [ ]:
?@simd

In [ ]:
function my_sum_simd(V)   
    s = 0.0  # s = zero(eltype(A))
    @simd for v in V
        s += v
    end
    s
end

j_bench_hand_simd = @benchmark my_sum_simd($V)
d_min["Julia hand-written simd"] = minimum(j_bench_hand_simd.times) / 1e6  # in milliseconds
d_med["Julia hand-written simd"] = median(j_bench_hand_simd.times) / 1e6

t = j_bench_hand_simd.times / 1e6 # times in milliseconds

histogram(t, bins=500,
             title="Benchmarks for Julia hand-written sum function with @smid",
             xlim=(min_t, max_t),
             xlabel="milliseconds", ylabel="count", label="")

### C with `gcc -ffast-math again`

In [ ]:
t = c_fastmath_bench.times / 1e6  # times in milliseconds

histogram(t, bins=500,
             title="Benchmarks for Julia hand-written sum function with @smid",
             xlim=(min_t, max_t),
             xlabel="milliseconds", ylabel="count", label="")

## 4.6 Sumary

In [ ]:
println("Median of time of computing sum(V)")
for (key, value) in sort(collect(d_med), by=last)
    println(rpad(key, 26, "."), lpad(round(value; digits=5), 6, "."))
end

println("\n\n\nMinimal time of computing sum(V)")
for (key, value) in sort(collect(d_min), by=last)
    println(rpad(key, 26, "."), lpad(round(value; digits=5), 6, "."))
end

# Don't work, still

In [ ]:
function ksintegrate(u₀, Lₓ, Δt, Nsteps, nsave);
    uⁿ = (1+0im)*u₀                      # force u to be complex
    Nₓ = length(uⁿ)                       # number of gridpoints
    kₓ = vcat(0:Nₓ/2 - 1, 0:0, -Nₓ/2+1:-1)  # integer wavenumbers: exp(2πikₓ x/L)
    α  = 2*pi*kₓ/Lₓ                       # real wavenumbers:    exp(iαx)
    D  = 1im*α                           # spectral D = d/dx operator 
    L  = α.^2 - α.^4                     # spectral L = -D^2 - D^4 operator
    G  = -0.5*D                          # spectral -1/2 D operator
    
    Nsave = div(Nsteps, nsave)+1         # number of saved u's, including t=0
    t = (0:Nsave-1)*(Δt*nsave)           # times of saved u's
    U = zeros(Nsave, Nₓ)                 # matrix of u(tᵢ, xⱼ) values
    U[1,:] = real(u₀)                    # assign initial condition to U
    s = 2                                # counter for saved data
    
    # construct diagonal matrices for LHS and RHS linear operators
    I   = ones(Nₓ)
    A⁻¹ = (I - Δt/2*L).^(-1)             
    B   = I + Δt/2*L
    
    # compute in-place FFTW plans
    FFT!  = plan_fft!(uⁿ,  flags=FFTW.ESTIMATE)
    IFFT! = plan_ifft!(uⁿ, flags=FFTW.ESTIMATE)

    # initialize nonlinear terms 
    Nuⁿ  = G.*fft(uⁿ.^2)      # set Nuⁿ = -1/2 d/dx (uⁿ)² = -u uₓ 
    Nuⁿ⁻¹ = copy(Nuⁿ)         # set Nuⁿ⁻¹ = Nuⁿ for first time step
    FFT!*uⁿ
    
    # timestepping loop
    for n = 0:Nsteps-1
        
        Nuⁿ⁻¹ .= Nuⁿ        # shift nonlinear term in time
        Nuⁿ  .= uⁿ         # store uⁿ in Nuⁿ in prep for collocation computation
        
        IFFT!*Nuⁿ          # transform to gridpt values of u
        Nuⁿ .= Nuⁿ.*Nuⁿ    # collocation calculation of u²
        FFT!*Nuⁿ           # transform u² back to spectral coeffs

        Nuⁿ .= G .* Nuⁿ      # compute  Nuⁿ = -1/2 d/dx u² = -u uₓ

        # Loop fusion! Julia unrolls this line into a single for-loop over vector elems,
        # avoiding the generation and allocation of temporary vectors you'd get in Matlab
        uⁿ .= A⁻¹ .* (B .* uⁿ .+ 3Δt/2 .* Nuⁿ .- Δt/2 .* Nuⁿ⁻¹)
        
        if mod(n, nsave) == 0
            U[s,:] = real(ifft(uⁿ))  # save into return matrix U 
            s += 1            
        end
    end
   
    t,U
end

In [ ]:

# set discretization parameters
Lx = 64π
Nx = 1024
Δt = 1/16
nsave = 8
Nsteps = 3200

# set initial condition
x = Lx*(0:Nx-1)/Nx
u₀ = cos.(x) + 0.1*sin.(x/8) + 0.002*cos.(x/32);

# compile the integrator function by running it one time step
t,U = ksintegrate(u₀, Lx, Δt, 8, nsave)

# integrate the PDE
t,U = ksintegrate(u₀, Lx, Δt, Nsteps, nsave) 

# plot results
heatmap(x,t, U, xlim=(x[1], x[end]), ylim=(t[1], t[end]), 
    xlabel="x", ylabel="t", title="u(x,t)", fillcolor=:bluesreds
)

In [ ]:
# set discretization parameters
Lx = 64π
Nx = 1024
Δt = 1/16
nsave = 8
Nsteps = 3200

# set initial condition
x = Lx*(0:Nx-1)/Nx
u₀ = cos.(x) + 0.1*sin.(x/8) + 0.002*cos.(x/32);

# compile the integrator function by running it one time step
t,U = ksintegrate(u₀, Lx, Δt, 8, nsave)

# integrate the PDE
t,U = ksintegrate(u₀, Lx, Δt, Nsteps, nsave) 

# plot results
heatmap(x,t, U, xlim=(x[1], x[end]), ylim=(t[1], t[end]), 
    xlabel="x", ylabel="t", title="u(x,t)", fillcolor=:bluesreds
)

# 6. User defined types
Exampled oryginaly by Andreas Noack [*Fast and Flexible Linear Algebra in Julia*](https://www.youtube.com/watch?v=VS0fnUOAKpI).

Consider field $\mathbb{Z} / p$ where $p$ is prime number. It is called Galois field $\textrm{GF}( p )$, we now implemented it in Julia.

In [ ]:
# Type definiton
struct GF{p, T} <: Number where {p, T<:Integer}
    rep::T  # Representation: intyger which holds the value of element in GF(p)
    
    function GF{p, T}(x::Integer) where {p, T<:Integer}
        return new(mod(x, p))
    end
end
GF{p}(x::T) where {p, T<:Integer} = GF{p, T}(x)

We now define some basic methods for $\textrm{GF}( p )$ that all Julia Numbers must have.

In [ ]:
import Base: convert, inv, one, promote_rule, show, zero

function call(::Type{GF{p}}, x::Integer) where p
    if !isprime(p)
        throw(ArgumentError("p must be prime"))
    end
    return GF{p, typeof(x)}(mod(x, p))
end

convert(::Type{GF{p, T}}, x::Integer) where {p, T} = GF{p}(x)
convert(::Type{GF{p}}, x::Integer) where p = GF{p}(x)
convert(::Type{GF{p, T}}, x::GF{p}) where {p, T} = GF{p, T}(x.rep)
promote_rule(::Type{GF{p, T1}}, ::Type{T2}) where {p, T1, T2<:Integer} = GF{p, promote_type(T1, T2)}

# To be able show and print GF(p)
show(io::IO, x::GF) = show(io, x.rep)

Defining arithmetic operations on $\textrm{GF}( p )$.

In [ ]:
GF{7}(9)

In [ ]:
GF{2}(4)

In [ ]:
typeof(GF{7}(0))

In [ ]:
GF{4}(7)

In [ ]:
typeof(GF{4}(5))

In [ ]:
GF{4, 5}

In [ ]:
x = GF{3}(4)

In [ ]:
x

In [ ]:
typeof(x)

In [ ]:
typeof(x.rep)

In [ ]:
GF{7}(2) + GF{7}(5)

In [ ]:
import Base: +

+(x::GF{p, T}, y::GF{p, T}) where {p, T} = GF{p, T}(x.rep + y.rep)

In [ ]:
GF{7}(2) + GF{7}(5)

We now use some eldritch metaprograming magic.

In [ ]:
import Base: -, *, isless

for op in (:+, :-, :*, :isless)  # Loops over ops, defining each in terms of integer ops mod p
    @eval begin
        ($op)(x::GF{p, T}, y::GF{p, T}) where {p, T} = GF{p, T}($(op)(x.rep, y.rep))
    end
end

We now definde inverse and divison $\div$. This requariers more work, because dividing by zero throws error.

In [ ]:
import Base: /

function inv(x::GF{p, T}) where {p, T}
    if x == zero(x)
        throw(DivideError())
    end
    r, u, v = gcdx(x.rep, p)
    GF{p, T}(u)
end
(/)(x::GF{p}, y::GF{p}) where p = x * inv(y);
abs(x::GF{p, T}) where {p, T} = x

Some $\textrm{GF}( 7 )$ arithmetics

In [ ]:
GF{3}(5) / GF{3}(6)

In [ ]:
x = GF{7}(9)   # x =  (9 mod 7) = 2
y = GF{7}(12)  # y = (12 mod 7) = 5

In [ ]:
@show x
@show y
@show x + y  # (2 + 5) mod 7 = 0
@show x - y  # (2 - 5) mod 7 = 4
@show x * y  # (2 * 5) mod 7 = 3
@show x / y  # (2 ÷ 5) mod 7 = 6, because 2 = (6 * 5) mod 7

In [ ]:
x = [GF{7}(rand(0:6)) for i = 1:3]

In [ ]:
y = [GF{7}(rand(0:6)) for i = 1:3]

In [ ]:
x + y

In [ ]:
x = [GF{7}(1) GF{7}(2) GF{7}(1)]

In [ ]:
y = [GF{7}(3), GF{7}(2), GF{7}(2)]

In [ ]:
y'

In [ ]:
Base.conj(x::GF{p,T}) where {p,T} = x

In [ ]:
y'

In [ ]:
subtypes(Number)

In [ ]:
subtypes(Real)

In [ ]:
subtypes(AbstractFloat)

In [ ]:
subtypes(GF)